onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_reg_controller/CLK
add wave -noupdate /tb_reg_controller/reset
add wave -noupdate /tb_reg_controller/PCSrc
add wave -noupdate /tb_reg_controller/PAddr
add wave -noupdate /tb_reg_controller/BUS_IN
add wave -noupdate /tb_reg_controller/BUS_OUT
add wave -noupdate /tb_reg_controller/done
add wave -noupdate /tb_reg_controller/TheRegController/Control/present_state
add wave -noupdate /tb_reg_controller/TheRegController/Control/instruction
add wave -noupdate /tb_reg_controller/TheRegController/Control/destination
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterA
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterB
add wave -noupdate /tb_reg_controller/TheRegController/CLK
add wave -noupdate /tb_reg_controller/TheRegController/reset
add wave -noupdate /tb_reg_controller/TheRegController/PCSrc
add wave -noupdate /tb_reg_controller/TheRegController/PAddr
add wave -noupdate /tb_reg_controller/TheRegController/BUS_IN
add wave -noupdate /tb_reg_controller/TheRegController/BUS_OUT
add wave -noupdate /tb_reg_controller/TheRegController/Done
add wave -noupdate /tb_reg_controller/TheRegController/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/LDA
add wave -noupdate /tb_reg_controller/TheRegController/LDB
add wave -noupdate /tb_reg_controller/TheRegController/OP
add wave -noupdate /tb_reg_controller/TheRegController/CIN
add wave -noupdate /tb_reg_controller/TheRegController/dataout
add wave -noupdate /tb_reg_controller/TheRegController/dataoutALU
add wave -noupdate /tb_reg_controller/TheRegController/doneint
add wave -noupdate /tb_reg_controller/TheRegController/busInzero
add wave -noupdate /tb_reg_controller/TheRegController/PCload
add wave -noupdate /tb_reg_controller/TheRegController/q
add wave -noupdate /tb_reg_controller/TheRegController/addr
add wave -noupdate /tb_reg_controller/TheRegController/instruction
add wave -noupdate /tb_reg_controller/TheRegController/destination
add wave -noupdate /tb_reg_controller/TheRegController/C_set
add wave -noupdate /tb_reg_controller/TheRegController/C_reset
add wave -noupdate /tb_reg_controller/TheRegController/Creg
add wave -noupdate /tb_reg_controller/TheRegController/Control/CLK
add wave -noupdate /tb_reg_controller/TheRegController/Control/reset
add wave -noupdate /tb_reg_controller/TheRegController/Control/instruction
add wave -noupdate /tb_reg_controller/TheRegController/Control/destination
add wave -noupdate /tb_reg_controller/TheRegController/Control/C_set
add wave -noupdate /tb_reg_controller/TheRegController/Control/C_reset
add wave -noupdate /tb_reg_controller/TheRegController/Control/PCload
add wave -noupdate /tb_reg_controller/TheRegController/Control/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/Control/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDA
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDB
add wave -noupdate /tb_reg_controller/TheRegController/Control/OP
add wave -noupdate /tb_reg_controller/TheRegController/Control/done
add wave -noupdate /tb_reg_controller/CLK
add wave -noupdate /tb_reg_controller/TheRegController/Control/present_state
add wave -noupdate /tb_reg_controller/TheRegController/Control/next_state
add wave -noupdate /tb_reg_controller/TheRegController/Control/doneint
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/reset
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/addr
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/PAddr
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/PCSrc
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/PCload
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/clk
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/address
add wave -noupdate /tb_reg_controller/TheRegController/ProgramCounter/address_mux
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/A
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/B
add wave -noupdate /tb_reg_controller/reset
add wave -noupdate /tb_reg_controller/done
add wave -noupdate /tb_reg_controller/PCSrc
add wave -noupdate /tb_reg_controller/PAddr
add wave -noupdate /tb_reg_controller/CLK
add wave -noupdate /tb_reg_controller/BUS_OUT
add wave -noupdate /tb_reg_controller/BUS_IN
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/CIN
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/OP
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/COUT
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/F
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/TheALU/ALUOut
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/CLK
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/reset
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/BUS_IN
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/CIN
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/LDA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/LDB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/OP
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/COUT
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/BUS_OUT
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/Mux1_RegA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/Mux2_RegB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterC
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/ALUOutput
add wave -noupdate /tb_reg_controller/TheRegController/Control/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/Control/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/Control/reset
add wave -noupdate /tb_reg_controller/TheRegController/Control/present_state
add wave -noupdate /tb_reg_controller/TheRegController/Control/PCload
add wave -noupdate /tb_reg_controller/TheRegController/Control/OP
add wave -noupdate /tb_reg_controller/TheRegController/Control/next_state
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDB
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDA
add wave -noupdate /tb_reg_controller/TheRegController/captureALU
add wave -noupdate /tb_reg_controller/TheRegController/Control/instruction
add wave -noupdate /tb_reg_controller/TheRegController/Control/doneint
add wave -noupdate /tb_reg_controller/TheRegController/Control/done
add wave -noupdate /tb_reg_controller/TheRegController/Control/destination
add wave -noupdate /tb_reg_controller/TheRegController/Control/CLK
add wave -noupdate /tb_reg_controller/TheRegController/Control/C_set
add wave -noupdate /tb_reg_controller/TheRegController/Control/C_reset
add wave -noupdate /tb_reg_controller/TheRegController/Control/C_in
add wave -noupdate /tb_reg_controller/TheRegController/Rom/rom
add wave -noupdate /tb_reg_controller/TheRegController/Rom/q
add wave -noupdate /tb_reg_controller/TheRegController/Rom/clk
add wave -noupdate /tb_reg_controller/TheRegController/Rom/addr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3349286 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 363
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2100 ns}
