onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_reg_controller/TheRegController/Control/present_state
add wave -noupdate /tb_reg_controller/CLK
add wave -noupdate /tb_reg_controller/reset
add wave -noupdate /tb_reg_controller/instruction
add wave -noupdate /tb_reg_controller/destination
add wave -noupdate /tb_reg_controller/start
add wave -noupdate /tb_reg_controller/BUS_IN
add wave -noupdate /tb_reg_controller/CIN
add wave -noupdate /tb_reg_controller/COUT
add wave -noupdate /tb_reg_controller/BUS_OUT
add wave -noupdate /tb_reg_controller/done
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterB
add wave -noupdate /tb_reg_controller/TheRegController/CLK
add wave -noupdate /tb_reg_controller/TheRegController/reset
add wave -noupdate /tb_reg_controller/TheRegController/instruction
add wave -noupdate /tb_reg_controller/TheRegController/destination
add wave -noupdate /tb_reg_controller/TheRegController/start
add wave -noupdate /tb_reg_controller/TheRegController/BUS_IN
add wave -noupdate /tb_reg_controller/TheRegController/CIN
add wave -noupdate /tb_reg_controller/TheRegController/COUT
add wave -noupdate /tb_reg_controller/TheRegController/BUS_OUT
add wave -noupdate /tb_reg_controller/TheRegController/done
add wave -noupdate /tb_reg_controller/TheRegController/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/LDA
add wave -noupdate /tb_reg_controller/TheRegController/LDB
add wave -noupdate /tb_reg_controller/TheRegController/OP
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/CLK
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/reset
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/BUS_IN
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/CIN
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/LDA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/LDB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/OP
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/COUT
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/BUS_OUT
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/Mux1_RegA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/Mux2_RegB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterA
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterB
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/RegisterC
add wave -noupdate /tb_reg_controller/TheRegController/TheRegDatapath/ALUOutput
add wave -noupdate /tb_reg_controller/TheRegController/Control/CLK
add wave -noupdate /tb_reg_controller/TheRegController/Control/reset
add wave -noupdate /tb_reg_controller/TheRegController/Control/instruction
add wave -noupdate /tb_reg_controller/TheRegController/Control/destination
add wave -noupdate /tb_reg_controller/TheRegController/Control/start
add wave -noupdate /tb_reg_controller/TheRegController/Control/SEL1
add wave -noupdate /tb_reg_controller/TheRegController/Control/SEL2
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDA
add wave -noupdate /tb_reg_controller/TheRegController/Control/LDB
add wave -noupdate /tb_reg_controller/TheRegController/Control/OP
add wave -noupdate /tb_reg_controller/TheRegController/Control/done
add wave -noupdate /tb_reg_controller/TheRegController/Control/present_state
add wave -noupdate /tb_reg_controller/TheRegController/Control/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3749393 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 437
configure wave -valuecolwidth 150
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {2975047 ps} {5215798 ps}
